M48
; DRILL file {KiCad 9.0.1} date 2025-07-01T00:29:04-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-07-01T00:29:04-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
%
G90
G05
T1
X129.41Y-67.015
X135.19Y-67.015
T2
X122.1Y-110.25
X122.15Y-63.75
X172.675Y-110.25
X172.7Y-82.0
M30
